apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.fullnameOverride  }}-orders
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orders-project.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.global.fullnameOverride  }}-redis-config
            - configMapRef:
                name: {{ .Values.global.fullnameOverride  }}-mongo-config
            - configMapRef:
                name: {{ .Values.global.fullnameOverride  }}-orders-config
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.fullnameOverride  }}-mongo-auth
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.fullnameOverride  }}-mongo-auth
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.fullnameOverride  }}-redis-auth
                  key: REDIS_PASSWORD
            - name: REDIS_URL
              value: redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)
            - name: MONGO_URL
              value: mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@$(MONGO_HOST):$(MONGO_PORT)
          startupProbe:
            httpGet:
              path: {{ .Values.readinessProbeUrl }}
              port: {{ .Values.containerPort }}
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbeUrl }}
              port: {{ .Values.containerPort }}
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbeUrl }}
              port: {{ .Values.containerPort }}
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 2
