apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.fullnameOverride  }}-orders-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orders-project.labels" . | nindent 4 }}
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
