line-length = 120
target-version = 'py313'
fix = false
include = [
    "src/**/*.py",
]

[lint]
select = ["I", "PL", "F401", "F841", "N", "R", "E501"]
ignore = []
fixable = ["ALL"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]

[lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[lint.pep8-naming]
classmethod-decorators = [
    "pydantic.validator",
    "pydantic.field_validator",
    "declared_attr",
    "expression",
    "comparator"
]