apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.fullnameOverride }}-notifications-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
data:
  ENVIRONMENT: {{ .Values.environment | quote }}
  DEBUG: {{ .Values.debug | quote }}
  CORS_ALLOW_ORIGINS: {{ .Values.cors.allowOrigins | toJson | quote }}
  CORS_ALLOW_METHODS: {{ .Values.cors.allowMethods | toJson | quote }}
  CORS_ALLOW_HEADERS: {{ .Values.cors.allowHeaders | toJson | quote }}
  ALLOWED_HOSTS: {{ .Values.allowedHosts | toJson | quote }}
