apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: databases
  labels:
    database: mongodb
spec:
  clusterIP: None
  selector:
    database: mongodb
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
