apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.fullnameOverride  }}-frontend-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orders-project.labels" . | nindent 4 }}
spec:
  selector:
    app: frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
