apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.fullnameOverride  }}-mongo-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orders-project.labels" . | nindent 4 }}
data:
  MONGO_INITDB_DATABASE: {{ .Values.global.mongo.database | quote }}
  MONGO_HOST: {{ .Values.global.fullnameOverride }}-{{ .Values.global.mongo.host }}
  MONGO_PORT: {{ .Values.global.mongo.port | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.fullnameOverride  }}-redis-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orders-project.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{ .Values.global.fullnameOverride }}-{{ .Values.global.redis.host }}
  REDIS_PORT: {{ .Values.global.redis.port | quote }}

