apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.fullnameOverride  }}-mongo-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orders-project.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.global.mongo.username | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.global.mongo.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.fullnameOverride  }}-redis-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orders-project.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.global.redis.password | b64enc | quote }}