replicaCount: 3
image:
  repository: kkaarroollm/delivery-service
  tag: latest
  pullPolicy: Always

containerPort: 8001
service:
  port: 80

resources: {}

environment: PRODUCTION
debug: false

livenessProbeUrl: api/v1/health/liveness
readinessProbeUrl: api/v1/health/readiness
