replicaCount: 3
image:
  repository: kkaarroollm/delivery-service
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8001
service:
  port: 80

resources: {}

environment: PRODUCTION
debug: false
