apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: backend 
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
        - name: frontend-container
          image: kkaarroollm/frontend-service:latest
          ports:
            - containerPort: 5173
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "150m"
              memory: "128Mi"
