
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-deployment
  labels:
    app: simulator
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - name: simulator
          image: kkaarroollm/simulator-service:latest
          envFrom:
            - configMapRef:
                name: redis-config
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: REDIS_PASSWORD
            - name: REDIS_URL
              value: redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)
