apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.fullnameOverride  }}-mongo-keyfile
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orders-project.labels" . | nindent 4 }}
type: Opaque
data:
  keyfile: {{ .Values.keyfile }}
