apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.fullnameOverride  }}-mongo-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orders-project.labels" . | nindent 4 }}
    database: mongo
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
