apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.fullnameOverride  }}-delivery-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orders-project.labels" . | nindent 4 }}
    app: delivery
spec:
  selector:
    app: delivery
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
