apiVersion: v2
name: orders-project
version: 0.1.0
description: A Helm chart for Kubernetes
appVersion: "1.16.0"
maintainers:
  - name: karol marszalek
    email: mkarol.4514@gmail.com
    url: https://www.github.com/kkaarroollm
dependencies:
  - name: ingress-nginx
    version: 4.12.1
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
  - name: mongodb
    version: 0.1.0
    repository: "file://charts/mongodb"
  - name: redis
    version: 0.1.0
    repository: "file://charts/redis"
  - name: orders
    version: 0.1.0
    repository: "file://charts/orders"
  - name: delivery
    version: 0.1.0
    repository: "file://charts/delivery"
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
  - name: simulator
    version: 0.1.0
    repository: "file://charts/simulator"
  - name: notifications
    version: 0.1.0
    repository: "file://charts/notifications"
