from src.interfaces.menu_repo_interface import IMenuItemRepository
from src.interfaces.menu_service_interface import IMenuService
from src.interfaces.order_repo_interface import IOrderRepository
from src.interfaces.order_service_interface import IOrderService
from src.interfaces.stream_consumer_interface import IRedisStreamConsumer
from src.interfaces.stream_publisher_interface import IRedisStreamPublisher
