from typing import Any, Protocol, runtime_checkable

from pymongo.asynchronous.client_session import AsyncClientSession

from src.schemas import MenuItemSchema


@runtime_checkable
class MenuItemRepositoryProtocol(Protocol):
    async def get_by_id(self, id: str, session: AsyncClientSession | None = None) -> MenuItemSchema | None: ...
    async def find_many(
        self, filter: dict[str, Any], session: AsyncClientSession | None = None, limit: int = 1000
    ) -> list[MenuItemSchema]: ...
    async def create(self, data: MenuItemSchema, session: AsyncClientSession | None = None) -> str: ...
    async def decrement_stock(self, item_id: str, quantity: int, session: AsyncClientSession) -> bool: ...
    async def increment_stock(self, item_id: str, quantity: int, session: AsyncClientSession) -> bool: ...
