namespace: prod

global:
  fullnameOverride: orders-project
  mongo:
    username: root
    password: SuperSecretMongoPassword123
    port: "27017"
    host: mongo-svc
    database: food-delivery

  redis:
    password: RedisPasswordSuperSecret321
    port: "6379"
    host: redis-svc

ingress-nginx:
  enabled: true
  controller:
    config:
      use-forwarded-headers: true
    ingressClassResource:
      enabled: false
    ingressClass: nginx


ingress:
  enabled: true
  host: frontend.localhost
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"


  # Add TLS configuration also

#### ADD TLS CONFIG TO INJECT INGRESS
  # tls:
  #   - secretName: frontend.localhost-tls
  #     hosts:
  #       - frontend.localhost

#### ADD CONFIG MAP INGRESS ADDITIONAL DATA
