namespace: prod

global:
  fullnameOverride: orders-project
  mongo:
    username: root
    password: SuperSecretMongoPassword123
    port: "27017"
    host: mongo-svc
    database: food-delivery

  redis:
    password: RedisPasswordSuperSecret321
    port: "6379"
    host: redis-svc

ingress-nginx:
  enabled: true
  controller:
    config:
      use-forwarded-headers: true
    ingressClassResource:
      enabled: true
    ingressClass: nginx


ingress:
  enabled: true
  host: orders.karolmarszalek.me
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-websocket: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "7200"

