apiVersion: v2
name: frontend
description: Frontend microservice chart
version: 0.1.0
appVersion: "1.0.0"
type: application
maintainers:
  - name: karol marszalek
    email: mkarol.4514@gmail.com
    url: https://www.github.com/kkaarroollm
