replicaCount: 3
image:
  repository: kkaarroollm/frontend-service
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 80
service:
  port: 80

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "150m"
    memory: "128Mi"
