replicaCount: 3

image:
  repository: mongo
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

keyfile: KzVZL2ovL012NFdlcWhXeG16b2FacUxrcTkzcmVMcStFM0xiZUorTkNHZ2lSd0hiWFQzOGxkbGw4SmlSYU0yOQpGeWRDMGhrb1pxdnBTdHhnYjlNSVJwOVc0SW1ScGJqSmtaMGlIUmVkN3dyMmlFbnQ1S2EvaDg0dlZGbmExS1BWCllWc2lacmdKWjk0ci9BRExhVGFNVkdpQUw2NTZHZWZMK2RCMDFodjNLVFp4M2ZYQzRJT2psKzN3NFVHa0JuN0wKdGx1Q0ZSM2F4R29wb0NqUkloWWlvdzRlYVEySlhlYVRQeEt6ZHd5NU1vV2xyd0VSYmxpQUtkdUxHZCtQNUhqcAoxTTErbnp0NGNDbGxRd2lIdTRUTzdYUUtmY25WcDlubGJWWThTRWJjYVZhU2ZQak9XVE9UQzh6ODZISm1ZWUtlCjBZYVY1OXhidmFKMkw3UDB4YUJqT0hzZzd3d1dvV3ZrVENOMURiSEo2Y1dYeXF4eitaK1k5bkIxNlozRDdZTGYKWVpuRmVUVkZrM1R2cm5SZ04xWFRPOGQxTnAxRjduaVdJVWtvN2U2YVRnM1d4ejBlcGtzdk9uRldkTEMwV2RvdgpRcFkxTWdaZlVHSWl3cURscE5GMmRVTTdZYlNPOU54bmg2cHN6c0FtUENzZy9jN1Q1cVFIOGZlY3NkcjBGaW1wCk9xdS9yL01QM0pJbTcxdTRwNHMzYlA4cWw2eE05QXZFRlc5aHJ2RXp4bFJoMmp5OS81a3ZPWU16S3E4RWE0bVgKZWJyZi9YU1hvdzA5QjBlaEV5YTdjU1FqcUhGYkUwakFRZkVFdzRxR2tGZGszZllHck9YeHkzSGdNVVdENjI1dgpsKzZJZFlJd1kwWmZuY1JCdnByaEhwS0YyYlpPSWQ5OUJLZzNNdWVROTQzdTFGOU4yZEpvbGt6MlQvUUFER21hCmZmYXlndVhzakk4VHJlSlJ6QnhLbzlzMXdQNWdFeFRnOFZVT0p4Q24xb2ZQN0l4ZGV5VlErTThUbThieWZVUDgKRW5LY25TQWJoMWk4OVFoVThYYmloL2svVXpUZVA1U25qbm1YaFQxcGNwUUI4ZzB6UjZOUlFvTmdpWkN3RE9MWgpObFRLVzAwVXZEQ25UUVJlYnpjYU5rUzA1OGg4L2RLemRmNy9SQkpmYk81YTBZR3BPeW1WeG5aV2lSMGdVSXQyCjNBbnE4MjlvZDM4S0pKY2pnYVByaXlacWF6a1pQUjdGVmdiS3V1YWlQUFh4UG9oaWtoM3Z2elFwcVNoOUhCRGgKUkFUZ2FlMGw0VVVzd0VRNEd4WnY2Nmt0MDg5ZXo0QnBvK2ZHeUNVV2habURzVDRJCg==

persistence:
  size: 5Gi

service:
  port: 27017
