apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.fullnameOverride  }}-simulator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orders-project.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - name: simulator
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.global.fullnameOverride }}-simulator-config
            - configMapRef:
                name: {{ .Values.global.fullnameOverride }}-redis-config
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.fullnameOverride }}-redis-auth
                  key: REDIS_PASSWORD
            - name: REDIS_URL
              value: redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)
