apiVersion: v2
name: notifications
description: Notifications microservice chart
version: 0.1.0
appVersion: "1.0.0"
type: application
maintainers:
  - name: karol marszalek
    email: mkarol.4514@gmail.com
    url: https://www.github.com/kkaarroollm
