replicaCount: 3
image:
  repository: kkaarroollm/notifications-service
  tag: latest
  pullPolicy: Always

containerPort: 8002
service:
  port: 80

resources: {}

environment: PRODUCTION
debug: false

cors:
  allowOrigins:
    - https://orders.karolmarszalek.me
  allowMethods:
    - GET
  allowHeaders:
    - "*"

allowedHosts:
  - orders.karolmarszalek.me

livenessProbeUrl: api/v1/health/liveness
readinessProbeUrl: api/v1/health/readiness
